### ISSUE TITLE
#oaddprem is not working

### ISSUE THREAD

**Issue by guiihzeraa1** [Urbaeexyz/wa-bot#11]
the command #oaddprem is not working, someone there to help me solve this?

**Comment by Urbaeexyz** [comment]
> the command #oaddprem is not working, someone there to help me solve this?

it's work if you reply message member

oaddprem = reply message member
odelprem = reply message member

addprem = input number
delprem = input number

example :
/addprem 62895334951166
/delprem 62895334951166
