### ISSUE TITLE
ChromePathNotSetError

### ISSUE THREAD

**Issue by syhdnlwy** [Urbaeexyz/wa-bot#15]
smua udh diinstal dgn lengkap ko msih error begini y udh ganti berkali2 versi linuxny tetep gitu jga..
mohon solusiny para suhuu..
![image](https://user-images.githubusercontent.com/50981821/113466727-2d276c00-9468-11eb-87c4-c13839b39d8c.png)

**Comment by Urbaeexyz** [comment]
![image](https://user-images.githubusercontent.com/75126993/113466915-b55a4100-9469-11eb-90e7-68827b3f213f.png)

**Comment by syhdnlwy** [comment]
![image](https://user-images.githubusercontent.com/50981821/113467061-b8096600-946a-11eb-9116-2c1950393f07.png)
Solusi bangg

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/50981821/113467061-b8096600-946a-11eb-9116-2c1950393f07.png)
> Solusi bangg? atau dihiraukan aj kan cma hilang font

Fontnya gnti ke ghosts

**Comment by Urbaeexyz** [comment]
Font : 'Ghosts'

**Comment by syhdnlwy** [comment]
gantiny dimana bg? index.js?
