### ISSUE TITLE
The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later.

### ISSUE THREAD

**Issue by mioscape** [Urbaeexyz/wa-bot#16]
First time install it, any idea how to fix it?

![Screenshot_20210404-180117947](https://user-images.githubusercontent.com/43681888/113506571-d60cbe80-956f-11eb-9669-98ed9bba0bc2.jpg)

**Comment by Urbaeexyz** [comment]
Linux?

**Comment by Urbaeexyz** [comment]
![Screenshot_20210404-180402.png](https://user-images.githubusercontent.com/75126993/113506631-2dab2a00-9570-11eb-940b-f3be879bb132.png)

**Comment by mioscape** [comment]
> Linux?

Debian

**Comment by mioscape** [comment]
Error changed

![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)

**Comment by Urbaeexyz** [comment]
> Error changed
> 
> ![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)
> 

Coba install nodejs versi 12.18.3 bang
Versi 13 ada problem

**Comment by mioscape** [comment]
> > Error changed
> > ![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)
> 
> Coba install nodejs versi 12.18.3 bang
> Versi 13 ada problem

Maaf lupa cd folder nya hehe

**Comment by Urbaeexyz** [comment]
https://www.google.com/amp/s/jagongoding.com/amp/linux/ubuntu/3-cara-mudah-install-nodejs-di-ubuntu/

**Comment by Urbaeexyz** [comment]
> > > Error changed
> > > ![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)
> > 
> > Coba install nodejs versi 12.18.3 bang
> > Versi 13 ada problem
> 
> Maaf lupa cd folder nya hehe

ckp tw

**Comment by mioscape** [comment]
> > Error changed
> > ![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)
> 
> Coba install nodejs versi 12.18.3 bang
> Versi 13 ada problem

Cara install dengan spesifik versi yang di tentukan gimana ya?

**Comment by mioscape** [comment]
> > Error changed
> > ![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)
> 
> Coba install nodejs versi 12.18.3 bang
> Versi 13 ada problem

Cara install dengan spesifik versi yang di tentukan gimana ya?

**Comment by Urbaeexyz** [comment]
> > > Error changed
> > > ![Screenshot_20210404-180703022](https://user-images.githubusercontent.com/43681888/113506707-a0b4a080-9570-11eb-96bc-adb9065c9e5b.jpg)
> > 
> > Coba install nodejs versi 12.18.3 bang
> > Versi 13 ada problem
> 
> Cara install dengan spesifik versi yang di tentukan gimana ya?

https://www.google.com/amp/s/jagongoding.com/amp/linux/ubuntu/3-cara-mudah-install-nodejs-di-ubuntu/
