### ISSUE TITLE
/welcome

### ISSUE THREAD

**Issue by syhdnlwy** [Urbaeexyz/wa-bot#17]
ni gmana yg bg udh di enable pas di grup /welcome ny ko pas ad yg join g ada pesan welcomeny
penting bgt ni bg gmana carany

**Comment by Urbaeexyz** [comment]
> ni gmana yg bg udh di enable pas di grup /welcome ny ko pas ad yg join g ada pesan welcomeny
> penting bgt ni bg gmana carany 

Masa si gada

**Comment by Urbaeexyz** [comment]
Ada errornya ga

**Comment by syhdnlwy** [comment]
di log ny si biasa aj
tpi di wa g ad respon pas ketik enable jga g ad respon
pas ad yg join jga biasa aj

**Comment by syhdnlwy** [comment]
udh2 bg salah ketik gua harusny /welcome enable bukan terpisah hehe

**Comment by Urbaeexyz** [comment]
> udh2 bg salah ketik gua harusny /welcome enable bukan terpisah hehe

![Screenshot_20210405-072617.png](https://user-images.githubusercontent.com/75126993/113525856-7818bf00-95e1-11eb-9bf1-24ab8099743b.png)

![Screenshot_20210405-073337.png](https://user-images.githubusercontent.com/75126993/113525859-7d760980-95e1-11eb-9717-f44bcab09138.png)

**Comment by syhdnlwy** [comment]
oiya sama ini bg pas welcomeny tu kok selamat datang di grup undefined ? knp tu bgg

**Comment by syhdnlwy** [comment]
pdhl udh di set grup name ny

**Comment by Urbaeexyz** [comment]
> oiya sama ini bg pas welcomeny tu kok selamat datang di grup undefined ? knp tu bgg

error dari sononya
gua juga kadang gitu
