### ISSUE TITLE
ini kenapa ya?

### ISSUE THREAD

**Issue by Nuser404** [Urbaeexyz/wa-bot#2]
![image](https://user-images.githubusercontent.com/50760394/110564215-0b93d700-817f-11eb-9454-3713e7b3ee93.png)

**Comment by Urbaeexyz** [comment]
> 
> ![image](https://user-images.githubusercontent.com/50760394/110564215-0b93d700-817f-11eb-9454-3713e7b3ee93.png)
> 
> 

Kalau masih error

npm rebuild --verbose sharp
