### ISSUE TITLE
prefix benar tapi no respon/saya melakukan kesalahan? butuh bantuan.

### ISSUE THREAD

**Issue by ramaarkel123** [Urbaeexyz/wa-bot#20]
![Screenshot (652)](https://user-images.githubusercontent.com/82738155/115130298-e4031a80-a018-11eb-9fb9-9a21fe07b2e9.png)

**Comment by Urbaeexyz** [comment]
check itu lgi di mode private/publik
kalo nomor lu dh jadi owner sih bakalan respon walaupun itu private

**Comment by Poks-A78** [comment]
bang saya juga tidak bisa, bot tidak jalan sama sekali padahal prefix sudah benar
, [](url)
![image](https://user-images.githubusercontent.com/83385049/116498571-3c1d0500-a8d4-11eb-962f-33efd0830df4.png)

**Comment by Urbaeexyz** [comment]
> bang saya juga tidak bisa, bot tidak jalan sama sekali padahal prefix sudah benar
> ,
> ![image](https://user-images.githubusercontent.com/83385049/116498571-3c1d0500-a8d4-11eb-962f-33efd0830df4.png)

coba fork ulang
