### ISSUE TITLE
fungsi menu tidak berfungsi dengan baik

### ISSUE THREAD

**Issue by nenofetch** [Urbaeexyz/wa-bot#23]
pas mau lihat fitur di menu bot dengan cara ketik /menu, tidak menampilkan hasil sama sekali malah muncul error sebagai berikut
![Screenshot from 2021-04-26 21-21-53](https://user-images.githubusercontent.com/22952560/116098941-aae03f80-a6d5-11eb-9c1e-aad95162d8a5.png)
terimakasih atas bantuannya

**Comment by Urbaeexyz** [comment]
> pas mau lihat fitur di menu bot dengan cara ketik /menu, tidak menampilkan hasil sama sekali malah muncul error sebagai berikut
> ![Screenshot from 2021-04-26 21-21-53](https://user-images.githubusercontent.com/22952560/116098941-aae03f80-a6d5-11eb-9c1e-aad95162d8a5.png)
> terimakasih atas bantuannya

check new update
