### ISSUE TITLE
Banyak menu / fitur yang error, (tidak dapat digunakan)

### ISSUE THREAD

**Issue by Poks-A78** [Urbaeexyz/wa-bot#24]
Banyak menu yang tidak dapat digunakan & error

**Comment by Urbaeexyz** [comment]
> Banyak menu yang tidak dapat digunakan & error
> 

Kalau ada fitur yang tidak bisa digunakan mungkin itu karena rest api yang digunakan sedang error

bisa tunjukin fitur apa yang error?
