### ISSUE TITLE
ada banyak / beberapa menu yang error dan tidak dapat digunakkan

### ISSUE THREAD

**Issue by Poks-A78** [Urbaeexyz/wa-bot#25]
Beberapa menu yang tidak dapat berfungsi, saya hanya menyebutkan beberapa menu, mungkin msh banyak lagi...
.startgif     
.nulis
.quotemaker
.katakasar
.klasmen
.tiktokpic
.artinama
.cekjodoh
.zodiak
.urgay
.stalkig
.memes
.chord
.puisi
.ceklokasi
.gcinfo
.dewabatch
.mtk
.google
.nyenye
.infogempa
.kbbi
.artimimpi
.family100
.caklontong
.tebakgambar
.glowtext
.blackpink
.stalktiktok
.quotesen
.infoalamat
.detail
.myzodiak
.imgtourl
.missing
.silverpb
.goldpb
.tendingtwit
.stalking
.pinterest
.tr
.postig
.tts
.pensilart
.kaiahelga
.unaa
.ranal
.googleimg
.searchwp
.pinimg
.do
.cersex
.wallhd
,jessicajane
.ruby
. Dan lain lain

Semua menu asupan & story wa Error
Downloader & Media kebanyakan tidak berfungsi
semua fitur anime tidak dapat digunakan.

Banyak conversi img / bot memberikan image ataupun data dalam file .json

Mungkin masih banyak .menu ataupun vitur error namun belum tersebutkan 
 Terima kasih atas perhatiannya 

Best Regard,
Poks - A78

**Comment by Urbaeexyz** [comment]
> Beberapa menu yang tidak dapat berfungsi, saya hanya menyebutkan beberapa menu, mungkin msh banyak lagi...
> .startgif     
> .nulis
> .quotemaker
> .katakasar
> .klasmen
> .tiktokpic
> .artinama
> .cekjodoh
> .zodiak
> .urgay
> .stalkig
> .memes
> .chord
> .puisi
> .ceklokasi
> .gcinfo
> .dewabatch
> .mtk
> .google
> .nyenye
> .infogempa
> .kbbi
> .artimimpi
> .family100
> .caklontong
> .tebakgambar
> .glowtext
> .blackpink
> .stalktiktok
> .quotesen
> .infoalamat
> .detail
> .myzodiak
> .imgtourl
> .missing
> .silverpb
> .goldpb
> .tendingtwit
> .stalking
> .pinterest
> .tr
> .postig
> .tts
> .pensilart
> .kaiahelga
> .unaa
> .ranal
> .googleimg
> .searchwp
> .pinimg
> .do
> .cersex
> .wallhd
> ,jessicajane
> .ruby
> . Dan lain lain
> 
> Semua menu asupan & story wa Error
> Downloader & Media kebanyakan tidak berfungsi
> semua fitur anime tidak dapat digunakan.
> 
> Banyak conversi img / bot memberikan image ataupun data dalam file .json
> 
> Mungkin masih banyak .menu ataupun vitur error namun belum tersebutkan 
>  Terima kasih atas perhatiannya 
> 
> 
> Best Regard,
> Poks - A78

Apikey ada?

![Screenshot_20210430-170539.png](https://user-images.githubusercontent.com/75126993/116680933-26095600-a961-11eb-8180-27db2f193dbe.png)

**Comment by Harsh-beep** [comment]
Hello,
ThankU for this wonderful bot.
My issue is that when I make bot join any group it doesn't leave when then members are below 10 and memberLimit is set to 10. It successfully join that group.
Could you please help.
