### ISSUE TITLE
why it does not work on termux????

### ISSUE THREAD

**Issue by anshuljai** [Urbaeexyz/wa-bot#27]
i am trying to install this sc in termux but it gives error....please resolve it

**Comment by anshuljai** [comment]
![Screenshot_2021-05-03-15-00-15-733_com termux](https://user-images.githubusercontent.com/24720160/116861200-5f231e00-ac20-11eb-8415-4b69a99c4171.jpg)
check this error pro
![Screenshot_2021-05-03-14-58-08-230_com termux](https://user-images.githubusercontent.com/24720160/116861218-677b5900-ac20-11eb-9db2-bb10d53757a4.jpg)
![Screenshot_2021-05-03-15-00-36-780_com termux](https://user-images.githubusercontent.com/24720160/116861231-6a764980-ac20-11eb-9ccc-6868aba1ebe1.jpg)

**Comment by Urbaeexyz** [comment]
> i am trying to install this sc in termux but it gives error....please resolve it

I don't think it will be work on termux

**Comment by anshuljai** [comment]
any solution on android???

**Comment by anshuljai** [comment]
any appp?

**Comment by anshuljai** [comment]
> > i am trying to install this sc in termux but it gives error....please resolve it
> 
> I don't think it will be work on termux

any app????

**Comment by anshuljai** [comment]
@Urbaeexyz??

**Comment by Urbaeexyz** [comment]
> any solution on android???

nope

**Comment by Urbaeexyz** [comment]
> > > i am trying to install this sc in termux but it gives error....please resolve it
> > 
> > I don't think it will be work on termux
> 
> any app????

Remote desktop

**Comment by Urbaeexyz** [comment]
RD client

**Comment by Harsh-beep** [comment]
> RD client

Could you please look into previous issue?
If you are working on it the please reply. I'll be waiting.
