### ISSUE TITLE
bot lu error pas npm install

### ISSUE THREAD

**Issue by SyauqiR** [Urbaeexyz/wa-bot#29]
npm ERR! code 1
npm ERR! path E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.4
npm ERR! node-pre-gyp info using node@15.14.0 | win32 | ia32
npm ERR! node-pre-gyp info check checked for "E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-win32-unknown-ia32.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.7.0 and node@15.14.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-win32-unknown-ia32.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | win32 | ia32
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | win32 | ia32
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python2" can be used
npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if Python is C:\Python37\python.exe
npm ERR! gyp ERR! find Python - "C:\Python37\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if Python is C:\Python27\python.exe
npm ERR! gyp ERR! find Python - "C:\Python27\python.exe" could not be run
npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python
npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:333:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:345:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:480:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:81:21)
npm ERR! gyp ERR! System Windows_NT 10.0.10240
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\KUMPULAN PARA BOT\\wa-bot-main\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=E:\\KUMPULAN PARA BOT\\wa-bot-main\\node_modules\\canvas\\build\\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
npm ERR! gyp ERR! cwd E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.10240
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\KUMPULAN PARA BOT\\wa-bot-main\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas
npm ERR! node-pre-gyp ERR! node -v v15.14.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.4
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\findo\AppData\Local\npm-cache\_logs\2021-05-01T01_26_58_386Z-debug.log

**Comment by Urbaeexyz** [comment]
> npm ERR! code 1
> npm ERR! path E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
> npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
> npm ERR! node-pre-gyp info it worked if it ends with ok
> npm ERR! node-pre-gyp info using node-pre-gyp@1.0.4
> npm ERR! node-pre-gyp info using node@15.14.0 | win32 | ia32
> npm ERR! node-pre-gyp info check checked for "E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node" (not found)
> npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-win32-unknown-ia32.tar.gz
> npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-win32-unknown-ia32.tar.gz
> npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.7.0 and node@15.14.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
> npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.7.0/canvas-v2.7.0-node-v88-win32-unknown-ia32.tar.gz
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@7.1.2
> npm ERR! gyp info using node@15.14.0 | win32 | ia32
> npm ERR! gyp info ok
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@7.1.2
> npm ERR! gyp info using node@15.14.0 | win32 | ia32
> npm ERR! gyp ERR! find Python
> npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
> npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
> npm ERR! gyp ERR! find Python checking if "python3" can be used
> npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
> npm ERR! gyp ERR! find Python checking if "python" can be used
> npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
> npm ERR! gyp ERR! find Python checking if "python2" can be used
> npm ERR! gyp ERR! find Python - "python2" is not in PATH or produced an error
> npm ERR! gyp ERR! find Python checking if Python is C:\Python37\python.exe
> npm ERR! gyp ERR! find Python - "C:\Python37\python.exe" could not be run
> npm ERR! gyp ERR! find Python checking if Python is C:\Python27\python.exe
> npm ERR! gyp ERR! find Python - "C:\Python27\python.exe" could not be run
> npm ERR! gyp ERR! find Python checking if the py launcher can be used to find Python
> npm ERR! gyp ERR! find Python - "py.exe" is not in PATH or produced an error
> npm ERR! gyp ERR! find Python
> npm ERR! gyp ERR! find Python **********************************************************
> npm ERR! gyp ERR! find Python You need to install the latest version of Python.
> npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> npm ERR! gyp ERR! find Python you can try one of the following options:
> npm ERR! gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
> npm ERR! gyp ERR! find Python (accepted by both node-gyp and npm)
> npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
> npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
> npm ERR! gyp ERR! find Python npm config set python "C:\Path\To\python.exe"
> npm ERR! gyp ERR! find Python For more information consult the documentation at:
> npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
> npm ERR! gyp ERR! find Python **********************************************************
> npm ERR! gyp ERR! find Python
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
> npm ERR! gyp ERR! stack at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:302:47)
> npm ERR! gyp ERR! stack at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
> npm ERR! gyp ERR! stack at PythonFinder. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:200:18)
> npm ERR! gyp ERR! stack at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:266:16)
> npm ERR! gyp ERR! stack at exithandler (node:child_process:333:5)
> npm ERR! gyp ERR! stack at ChildProcess.errorhandler (node:child_process:345:5)
> npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:369:20)
> npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
> npm ERR! gyp ERR! stack at onErrorNT (node:internal/child_process:480:16)
> npm ERR! gyp ERR! stack at processTicksAndRejections (node:internal/process/task_queues:81:21)
> npm ERR! gyp ERR! System Windows_NT 10.0.10240
> npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node" "--module_name=canvas" "--module_path=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
> npm ERR! gyp ERR! cwd E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas
> npm ERR! gyp ERR! node -v v15.14.0
> npm ERR! gyp ERR! node-gyp -v v7.1.2
> npm ERR! gyp ERR! not ok
> npm ERR! node-pre-gyp ERR! build error
> npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas\build\Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
> npm ERR! node-pre-gyp ERR! stack at ChildProcess. (E:\KUMPULAN PARA BOT\wa-bot-main\node_modules@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
> npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:369:20)
> npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1067:16)
> npm ERR! node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
> npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.10240
> npm ERR! node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\@mapbox\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
> npm ERR! node-pre-gyp ERR! cwd E:\KUMPULAN PARA BOT\wa-bot-main\node_modules\canvas
> npm ERR! node-pre-gyp ERR! node -v v15.14.0
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.4
> npm ERR! node-pre-gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\findo\AppData\Local\npm-cache_logs\2021-05-01T01_26_58_386Z-debug.log

ignore aja
11/12 kek elaina
gua dulu make elaina juga gitu dlu, cuman di hirauin aja cok

**Comment by SyauqiR** [comment]
coba send wa lu,biar gw tanya lewat wa aja
udah lupa gw wkwk

**Comment by SyauqiR** [comment]
kalau langsung di npm start kek gini

- D:\whatsapp-bot-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (D:\whatsapp-bot-main\index.js:1:28)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\whatsapp-bot-main\\index.js' ]
}

**Comment by Urbaeexyz** [comment]
> kalau langsung di npm start kek gini
> 
> * D:\whatsapp-bot-main\index.js
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:769:27)
>   at Module.require (node:internal/modules/cjs/loader:996:19)
>   at require (node:internal/modules/cjs/helpers:92:18)
>   at Object. (D:\whatsapp-bot-main\index.js:1:28)
>   at Module._compile (node:internal/modules/cjs/loader:1092:14)
>   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
>   at Module.load (node:internal/modules/cjs/loader:972:32)
>   at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>   at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ 'D:\whatsapp-bot-main\index.js' ]
>   }

coba ini
`npm install -g node-pre-gyp`
abis itu
`npm install`
kalo masih error
coba ini 
`node-pre-gyp install --fallback-to-build`
