### ISSUE TITLE
npm Install (Puppeteer Error)

### ISSUE THREAD

**Issue by bsmarty978** [Urbaeexyz/wa-bot#31]
![issue](https://user-images.githubusercontent.com/37466081/119126494-b7478600-ba50-11eb-8b98-cbe378a3c4cf.png)

While npm install I am getting this error plzz help me out

**Comment by Urbaeexyz** [comment]
> ![issue](https://user-images.githubusercontent.com/37466081/119126494-b7478600-ba50-11eb-8b98-cbe378a3c4cf.png)
> 
> While npm install I am getting this error plzz help me out

which version of nodejs you used?
