### ISSUE TITLE
Npm Start Error

### ISSUE THREAD

**Issue by Fadhila36** [Urbaeexyz/wa-bot#32]
TypeError: Cannot read property '0' of undefined
    at Object.keyword (D:\kerjaan\belajar\wa-bot\node_modules\ansi-styles\index.js:15:39)
    at Chalk.<anonymous> (D:\kerjaan\belajar\wa-bot\node_modules\chalk\source\index.js:85:77)
    at color (D:\kerjaan\belajar\wa-bot\function\index.js:11:52)
    at start (D:\kerjaan\belajar\wa-bot\index.js:13:21)
    at D:\kerjaan\belajar\wa-bot\index.js:51:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5) #

![Screenshot_10](https://user-images.githubusercontent.com/37483304/119354945-d94e3c00-bcce-11eb-8637-a2a2d7028c9c.png)

kenapa muncul itu ya gan?

**Comment by Urbaeexyz** [comment]
> TypeError: Cannot read property '0' of undefined
> at Object.keyword (D:\kerjaan\belajar\wa-bot\node_modules\ansi-styles\index.js:15:39)
> at Chalk. (D:\kerjaan\belajar\wa-bot\node_modules\chalk\source\index.js:85:77)
> at color (D:\kerjaan\belajar\wa-bot\function\index.js:11:52)
> at start (D:\kerjaan\belajar\wa-bot\index.js:13:21)
> at D:\kerjaan\belajar\wa-bot\index.js:51:22
> at processTicksAndRejections (internal/process/task_queues.js:93:5) #
> 
> ![Screenshot_10](https://user-images.githubusercontent.com/37483304/119354945-d94e3c00-bcce-11eb-8637-a2a2d7028c9c.png)
> 
> kenapa muncul itu ya gan?

coba ini
```npm i --save chalk@latest```

**Comment by Fadhila36** [comment]
> > TypeError: Cannot read property '0' of undefined
> > at Object.keyword (D:\kerjaan\belajar\wa-bot\node_modules\ansi-styles\index.js:15:39)
> > at Chalk. (D:\kerjaan\belajar\wa-bot\node_modules\chalk\source\index.js:85:77)
> > at color (D:\kerjaan\belajar\wa-bot\function\index.js:11:52)
> > at start (D:\kerjaan\belajar\wa-bot\index.js:13:21)
> > at D:\kerjaan\belajar\wa-bot\index.js:51:22
> > at processTicksAndRejections (internal/process/task_queues.js:93:5) #
> > ![Screenshot_10](https://user-images.githubusercontent.com/37483304/119354945-d94e3c00-bcce-11eb-8637-a2a2d7028c9c.png)
> > kenapa muncul itu ya gan?
> 
> coba ini
> `npm i --save chalk@latest`

masih sama, masih error sama kaya yang di atas

**Comment by Urbaeexyz** [comment]
> > > TypeError: Cannot read property '0' of undefined
> > > at Object.keyword (D:\kerjaan\belajar\wa-bot\node_modules\ansi-styles\index.js:15:39)
> > > at Chalk. (D:\kerjaan\belajar\wa-bot\node_modules\chalk\source\index.js:85:77)
> > > at color (D:\kerjaan\belajar\wa-bot\function\index.js:11:52)
> > > at start (D:\kerjaan\belajar\wa-bot\index.js:13:21)
> > > at D:\kerjaan\belajar\wa-bot\index.js:51:22
> > > at processTicksAndRejections (internal/process/task_queues.js:93:5) #
> > > ![Screenshot_10](https://user-images.githubusercontent.com/37483304/119354945-d94e3c00-bcce-11eb-8637-a2a2d7028c9c.png)
> > > kenapa muncul itu ya gan?
> > 
> > 
> > coba ini
> > `npm i --save chalk@latest`
> 
> masih sama, masih error sama kaya yang di atas

kalo bisa nodejs pake yg versi 12 atau yg baru
jangan yg versi 13
