### ISSUE TITLE
 messageLog is not defined

### ISSUE THREAD

**Issue by Cyber-Akiya** [Urbaeexyz/wa-bot#35]
C:\Users\MY\Downloads\wa-bot\index.js:46
        messageLog(anal.fromMe, anal.type)
        ^

ReferenceError: messageLog is not defined
    at C:\Users\MY\Downloads\wa-bot\index.js:46:9
    at Client.<anonymous> (C:\Users\MY\Downloads\wa-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:550:92)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\MY\Downloads\wa-bot\node_modules\@open-wa\wa-automate\dist\api\Client.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
![Screenshot (14)](https://user-images.githubusercontent.com/85092955/121908501-b30a4200-cd4a-11eb-9e8d-bb1b932f5b87.png)

**Comment by Urbaeexyz** [comment]
delete that man on index.js

**Comment by Urbaeexyz** [comment]
> C:\Users\MY\Downloads\wa-bot\index.js:46
> messageLog(anal.fromMe, anal.type)
> ^
> 
> ReferenceError: messageLog is not defined
> at C:\Users\MY\Downloads\wa-bot\index.js:46:9
> at Client. (C:\Users\MY\Downloads\wa-bot\node_modules@open-wa\wa-automate\dist\api\Client.js:550:92)
> at Generator.next ()
> at fulfilled (C:\Users\MY\Downloads\wa-bot\node_modules@open-wa\wa-automate\dist\api\Client.js:24:58)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ![Screenshot (14)](https://user-images.githubusercontent.com/85092955/121908501-b30a4200-cd4a-11eb-9e8d-bb1b932f5b87.png)

update!

**Comment by Cyber-Akiya** [comment]
> delete that man on index.js

wich one ?
can I contact you on WhatsApp?

**Comment by Urbaeexyz** [comment]
> > delete that man on index.js
> 
> wich one ?
> can I contact you on WhatsApp?

on index.js
just click the word "hope this helpful"

**Comment by Cyber-Akiya** [comment]
> > > delete that man on index.js
> > 
> > 
> > wich one ?
> > can I contact you on WhatsApp?
> 
> on index.js
> just click the word "hope this helpful"

After scanning the qr code and if I send a command it shows above error, After that I deleted on index.js as you said, now bot is not responding to my commands..!

wa.me/94701987714 plz contact me on whatsapp

**Comment by Urbaeexyz** [comment]
> > > > delete that man on index.js
> > > 
> > > 
> > > wich one ?
> > > can I contact you on WhatsApp?
> > 
> > 
> > on index.js
> > just click the word "hope this helpful"
> 
> After scanning the qr code and if I send a command it shows above error, After that I deleted on index.js as you said, now bot is not responding to my commands..!
> 
> wa.me/94701987714 plz contact me on whatsapp

check update "wrong line"

**Comment by Urbaeexyz** [comment]
> > > > delete that man on index.js
> > > 
> > > 
> > > wich one ?
> > > can I contact you on WhatsApp?
> > 
> > 
> > on index.js
> > just click the word "hope this helpful"
> 
> After scanning the qr code and if I send a command it shows above error, After that I deleted on index.js as you said, now bot is not responding to my commands..!
> 
> wa.me/94701987714 plz contact me on whatsapp

hello, is it working?
if it's working please close this issue
