### ISSUE TITLE
Session Failed 

### ISSUE THREAD

**Issue by aomineee** [Urbaeexyz/wa-bot#38]
bang tolongin gw kenapa dari kemaren session failed mulu ya?

**Comment by Urbaeexyz** [comment]
> bang tolongin gw kenapa dari kemaren session failed mulu ya?

screenshot ada?

**Comment by Urbaeexyz** [comment]
> bang tolongin gw kenapa dari kemaren session failed mulu ya?

tdi saya nyoba clone juga pas npm start juga problemnya sama kek lu
coba gini
deleted file URBAE.data.json (kalo ada)
kalo ga ada langsung gini
`npm install @open-wa/wa-automate@latest`

**Comment by Urbaeexyz** [comment]
> bang tolongin gw kenapa dari kemaren session failed mulu ya?

bisa ga?
