### ISSUE TITLE
ini fitur play knp bang?

### ISSUE THREAD

**Issue by yoga875** [Urbaeexyz/wa-bot#39]
invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0

**Comment by Urbaeexyz** [comment]
> invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0

ntar gua benerin

**Comment by yoga875** [comment]
> > invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0
> 
> ntar gua benerin

Siap ngab🙏

**Comment by Urbaeexyz** [comment]
> > > invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0
> > 
> > 
> > ntar gua benerin
> 
> Siap ngab

udahh
coba lah
kalo error blg aja

**Comment by Urbaeexyz** [comment]
> > > invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0
> > 
> > 
> > ntar gua benerin
> 
> Siap ngab

bisa ga?

**Comment by yoga875** [comment]
> > > > invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0
> > > 
> > > 
> > > ntar gua benerin
> > 
> > 
> > Siap ngab
> 
> bisa ga?

Bisa ngab thanks

**Comment by Urbaeexyz** [comment]
> > > > > invalid json response body at https://api.zeks.xyz/api/yts?q=black%20catcher&apikey=administrator reason: Unexpected token < in JSON at position 0
> > > > 
> > > > 
> > > > ntar gua benerin
> > > 
> > > 
> > > Siap ngab
> > 
> > 
> > bisa ga?
> 
> Bisa ngab thanks

close issues nya
