### ISSUE TITLE
menunya knp bang?:'v

### ISSUE THREAD

**Issue by yoga875** [Urbaeexyz/wa-bot#40]
[EXEC] 11/07/21 15:51:22 !menu [0] from ĻĪĻĪȚH
[EROR] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:124:11)
    at Url.parse (url.js:170:3)
    at Object.urlParse [as parse] (url.js:157:13)
    at dispatchHttpRequest (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:91:22)
    at new Promise (<anonymous>)
    at httpAdapter (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:46:10)
    at dispatchRequest (c:\wa-bot-main\node_modules\axios\lib\core\dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by Urbaeexyz** [comment]
> [EXEC] 11/07/21 15:51:22 !menu [0] from ĻĪĻĪȚH
> [EROR] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object
> at validateString (internal/validators.js:124:11)
> at Url.parse (url.js:170:3)
> at Object.urlParse [as parse] (url.js:157:13)
> at dispatchHttpRequest (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:91:22)
> at new Promise ()
> at httpAdapter (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:46:10)
> at dispatchRequest (c:\wa-bot-main\node_modules\axios\lib\core\dispatchRequest.js:52:10)
> at processTicksAndRejections (internal/process/task_queues.js:95:5) {
> code: 'ERR_INVALID_ARG_TYPE'

njir coba ss

**Comment by yoga875** [comment]
> > [EXEC] 11/07/21 15:51:22 !menu [0] from ĻĪĻĪȚH
> > [EROR] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object
> > at validateString (internal/validators.js:124:11)
> > at Url.parse (url.js:170:3)
> > at Object.urlParse [as parse] (url.js:157:13)
> > at dispatchHttpRequest (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:91:22)
> > at new Promise ()
> > at httpAdapter (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:46:10)
> > at dispatchRequest (c:\wa-bot-main\node_modules\axios\lib\core\dispatchRequest.js:52:10)
> > at processTicksAndRejections (internal/process/task_queues.js:95:5) {
> > code: 'ERR_INVALID_ARG_TYPE'
> 
> njir coba ss

![Screenshot_20210711-210331_Microsoft Remote Desktop](https://user-images.githubusercontent.com/72691602/125198288-8551e380-e28b-11eb-823e-4ee7785f7c97.jpg)

**Comment by Urbaeexyz** [comment]
> > > [EXEC] 11/07/21 15:51:22 !menu [0] from ĻĪĻĪȚH
> > > [EROR] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received an instance of Object
> > > at validateString (internal/validators.js:124:11)
> > > at Url.parse (url.js:170:3)
> > > at Object.urlParse [as parse] (url.js:157:13)
> > > at dispatchHttpRequest (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:91:22)
> > > at new Promise ()
> > > at httpAdapter (c:\wa-bot-main\node_modules\axios\lib\adapters\http.js:46:10)
> > > at dispatchRequest (c:\wa-bot-main\node_modules\axios\lib\core\dispatchRequest.js:52:10)
> > > at processTicksAndRejections (internal/process/task_queues.js:95:5) {
> > > code: 'ERR_INVALID_ARG_TYPE'
> > 
> > 
> > njir coba ss
> 
> ![Screenshot_20210711-210331_Microsoft Remote Desktop](https://user-images.githubusercontent.com/72691602/125198288-8551e380-e28b-11eb-823e-4ee7785f7c97.jpg)

masih error kah?

**Comment by Urbaeexyz** [comment]
klo ga salah itu error dri aruga.getProfilePicFromServer
dlu perasaan gada error errornya

**Comment by yoga875** [comment]
> klo ga salah itu error dri aruga.getProfilePicFromServer
> dlu perasaan gada error errornya

Terus gmn bang? Saran dong

**Comment by Stive889** [comment]
Saya memiliki kesalahan yang sama selama 20 jam, ternyata ada sesuatu dengan perpustakaan karena tidak ada yang dimodifikasi, hanya gagal saat menggunakan #menu, fungsi lainnya sangat baik

**Comment by Stive889** [comment]
![image](https://user-images.githubusercontent.com/26675985/125211267-284a3380-e273-11eb-9254-48c8426c47c1.png)

In the await line is where the library is giving an error, the #menuadmin works correctly.

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/26675985/125211267-284a3380-e273-11eb-9254-48c8426c47c1.png)
> 
> In the await line is where the library is giving an error, the #menuadmin works correctly.

check the updates pls

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/26675985/125211267-284a3380-e273-11eb-9254-48c8426c47c1.png)
> 
> In the await line is where the library is giving an error, the #menuadmin works correctly.

i have change it but idk if it's gonna fix it
if it's fix the problem please tell me on this issue

**Comment by Stive889** [comment]
yes, it was completely resolved, in the last commit, I had an older version and just changed the menu completely. thank you very much for always being available

**Comment by Urbaeexyz** [comment]
> yes, it was completely resolved, in the last commit, I had an older version and just changed the menu completely. thank you very much for always being available

you're welcome mate
