### ISSUE TITLE
tolong saya.

### ISSUE THREAD

**Issue by aomineee** [Urbaeexyz/wa-bot#41]
![image](https://user-images.githubusercontent.com/87003965/125301360-1b057580-e355-11eb-9261-ed3f850ec718.png)
Bang ini kenapa ?

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/87003965/125301360-1b057580-e355-11eb-9261-ed3f850ec718.png)
> Bang ini kenapa ?

pake nodejs versi LTS yg rekomendasi

**Comment by Urbaeexyz** [comment]
baca readme

**Comment by Urbaeexyz** [comment]
https://github.com/Urbaeexyz/wa-bot#Requirements

**Comment by aomineee** [comment]
tetap gabisa bang udah install malah pas npm start masih kayak gitu

**Comment by Urbaeexyz** [comment]
> tetap gabisa bang udah install malah pas npm start masih kayak gitu

coba clone ulang

pas npm install ada yg error ga?

**Comment by Urbaeexyz** [comment]
rdp kan?

**Comment by aomineee** [comment]
bukan rdp bang

**Comment by Urbaeexyz** [comment]
> bukan rdp bang

terus make apa?

**Comment by Urbaeexyz** [comment]
> bukan rdp bang

gw close ya
kalo ada masalah reply ae
