### ISSUE TITLE
the · play and · play2 commands do not work in linux server

### ISSUE THREAD

**Issue by Stive889** [Urbaeexyz/wa-bot#42]
![image](https://user-images.githubusercontent.com/26675985/125369623-9b72a900-e34a-11eb-8af9-e975d234cd67.png)
![image](https://user-images.githubusercontent.com/26675985/125369645-acbbb580-e34a-11eb-8a70-a00879c7f75d.png)

I tested on my windows laptop and it works correctly but when trying on my Linux server it sends the songs null.html and in play2 it gives an error

I'd appreciate if you could take a look.

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/26675985/125369623-9b72a900-e34a-11eb-8af9-e975d234cd67.png)
> ![image](https://user-images.githubusercontent.com/26675985/125369645-acbbb580-e34a-11eb-8a70-a00879c7f75d.png)
> 
> I tested on my windows laptop and it works correctly but when trying on my Linux server it sends the songs null.html and in play2 it gives an error
> 
> I'd appreciate if you could take a look.

yeah it's return error from rest api

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/26675985/125369623-9b72a900-e34a-11eb-8af9-e975d234cd67.png)
> ![image](https://user-images.githubusercontent.com/26675985/125369645-acbbb580-e34a-11eb-8a70-a00879c7f75d.png)
> 
> I tested on my windows laptop and it works correctly but when trying on my Linux server it sends the songs null.html and in play2 it gives an error
> 
> I'd appreciate if you could take a look.

have a screenshot when it work on windows?

**Comment by Stive889** [comment]
yes!!!
![image](https://user-images.githubusercontent.com/26675985/125372502-425a4380-e351-11eb-9ecb-9c848f1b4f9b.png)

**Comment by Urbaeexyz** [comment]
> yes!!!
> ![image](https://user-images.githubusercontent.com/26675985/125372502-425a4380-e351-11eb-9ecb-9c848f1b4f9b.png)

is it new?

**Comment by Stive889** [comment]
It is the same code as the last version, only translated into Spanish which is my native language.


case prefix+'play'://silahkan kalian custom sendiri jika ada yang ingin diubah
           if (args.length == 0) return aruga.reply(from, `Para buscar canciones de youtube\n\nUsar: ${prefix}play título de la canción`, id)
           fetchJson(`http://docs-jojo.herokuapp.com/api/yt-search?q=${body.slice(6)}`)
			//fetchJson(`https://api.zeks.xyz/api/yts?q=${body.slice(6)}&apikey=${apikeyvinz}`)
            .then(async (res) => {
				console.log(color(`Nombre : ${pushname}\nNumero : ${serial.replace('@c.us', '')}\nJudul: ${res.result.result[0].title}\nDurasi: ${res.result.result[0].duration} detik`, 'aqua'))
				const thumbsd = res.result.result[0].thumbnails[0].url
				const thumbhd = res.result.result[0].thumbnails[1].url
			if (thumbhd == 0 || thumbhd == undefined) {
				var thumbnih = thumbsd
			} else {
				var thumbnih = thumbhd
			}
				//console.log(color(`Nickname : ${pushname}\nNomor : ${serial.replace('@c.us', '')}\nJudul: ${res.result[0].video.title}\nDurasi: ${res.result[0].video.duration} detik`, 'aqua'))
                 /*await aruga.sendFileFromUrl(from, res.data.result.result[0].thumbnails[0].url, ``, `「 *PLAY* 」\n\nJudul: ${res.data.result.result[0].title}\nDurasi: ${res.data.result.result[0].duration} detik\nViews: ${res.data.result.result[0].viewCount.short}\nUploaded: ${res.data.result.result[0].publishedTime}\nChannel: ${res.data.result.result[0].channel.name}\n\n*_Wait, lagi ngirim Audionya_*`, id)*/
				 //await aruga.sendFileFromUrl(from, res.result[0].video.thumbnail_src, 'thumb.jpg', `「 *PLAY* 」\n\n*Title:* ${res.result[0].video.title}\n*Duration:* ${res.result[0].video.duration} detik\n*Views:* ${res.result[0].video.views}\n*Uploaded:* ${res.result[0].video.upload_date}\n*Channel:* ${res.result[0].uploader.username}\n*Verified Channel:* ${res.result[0].uploader.verified}\n*Url:* ${res.result[0].video.url}\n\n*_Waitt, lagi ngirim Audionyaa_*`, id)
				await aruga.sendFileFromUrl(from, thumbnih, 'thumb.jpg', `「 *PLAY* 」\n\n*Titulo:* ${res.result.result[0].title}\n*Duracion:* ${res.result.result[0].duration} Min\n*Views:* ${res.result.result[0].viewCount.short}\n*Subido:* ${res.result.result[0].publishedTime}\n*Canal:* ${res.result.result[0].channel.name}\n*Url:* ${res.result.result[0].link}\n\n*_Espere... estamos creando su Audio_*`, id)
				 rugaapi.ymp3(`https://youtu.be/${res.result.result[0].id}`)
                .then(async(res) => {
				if (res.status == false) return aruga.reply(from, res.result, id)
				const playlink = res.result
				 //var playlinks = await axios.get(`https://urbaee-xyz.herokuapp.com/api/short/tiny?url=${res.}&apikey=Urbaeexyz`)
				 //var linkplay = playlinks.data.result.link
				 //if (!isPrem) return aruga.reply(from, `Karena anda bukan user Premium, silahkan download menggunakan link\n\nLink: ${linkplay}`, id)
				aruga.sendFileFromUrl(from, playlink, '', '', id)
                                .catch(() => {
                                        aruga.reply(from, 'Error', id)
                                   })
                                })
                        })
						.catch(err => {
							console.log(err)
							aruga.reply(from, err.message, id)
						})
                        break

**Comment by Urbaeexyz** [comment]
> It has about a month so I think, It is the same code as the last version, only translated into Spanish which is my native language.
> 
> case prefix+'play'://silahkan kalian custom sendiri jika ada yang ingin diubah
> if (args.length == 0) return aruga.reply(from, `Para buscar canciones de youtube\n\nUsar: ${prefix}play título de la canción`, id)
> fetchJson(`http://docs-jojo.herokuapp.com/api/yt-search?q=${body.slice(6)}`)
> //fetchJson(`https://api.zeks.xyz/api/yts?q=${body.slice(6)}&apikey=${apikeyvinz}`)
> .then(async (res) => {
> console.log(color(`Nombre : ${pushname}\nNumero : ${serial.replace('@c.us', '')}\nJudul: ${res.result.result[0].title}\nDurasi: ${res.result.result[0].duration} detik`, 'aqua'))
> const thumbsd = res.result.result[0].thumbnails[0].url
> const thumbhd = res.result.result[0].thumbnails[1].url
> if (thumbhd == 0 || thumbhd == undefined) {
> var thumbnih = thumbsd
> } else {
> var thumbnih = thumbhd
> }
> //console.log(color(`Nickname : ${pushname}\nNomor : ${serial.replace('@c.us', '')}\nJudul: ${res.result[0].video.title}\nDurasi: ${res.result[0].video.duration} detik`, 'aqua'))
> /_await aruga.sendFileFromUrl(from, res.data.result.result[0].thumbnails[0].url, ``, `「 *PLAY* 」\n\nJudul: ${res.data.result.result[0].title}\nDurasi: ${res.data.result.result[0].duration} detik\nViews: ${res.data.result.result[0].viewCount.short}\nUploaded: ${res.data.result.result[0].publishedTime}\nChannel: ${res.data.result.result[0].channel.name}\n\n*_Wait, lagi ngirim Audionya_*`, id)_/
> //await aruga.sendFileFromUrl(from, res.result[0].video.thumbnail_src, 'thumb.jpg', `「 _PLAY_ 」\n\n_Title:_ ${res.result[0].video.title}\n_Duration:_ ${res.result[0].video.duration} detik\n_Views:_ ${res.result[0].video.views}\n_Uploaded:_ ${res.result[0].video.upload_date}\n_Channel:_ ${res.result[0].uploader.username}\n_Verified Channel:_ ${res.result[0].uploader.verified}\n_Url:_ ${res.result[0].video.url}\n\n*_Waitt, lagi ngirim Audionyaa__`, id) await aruga.sendFileFromUrl(from, thumbnih, 'thumb.jpg', `「 _PLAY_ 」\n\n_Titulo:* ${res.result.result[0].title}\n_Duracion:_ ${res.result.result[0].duration} Min\n_Views:_ ${res.result.result[0].viewCount.short}\n_Subido:_ ${res.result.result[0].publishedTime}\n_Canal:_ ${res.result.result[0].channel.name}\n_Url:_ ${res.result.result[0].link}\n\n*_Espere... estamos creando su Audio_*`, id)
> rugaapi.ymp3(`[https://youtu.be/${res.result.result[0].id}`](https://youtu.be/$%7Bres.result.result%5B0%5D.id%7D%60))
> .then(async(res) => {
> if (res.status == false) return aruga.reply(from, res.result, id)
> const playlink = res.result
> //var playlinks = await axios.get(`[https://urbaee-xyz.herokuapp.com/api/short/tiny?url=${res.}&apikey=Urbaeexyz`](https://urbaee-xyz.herokuapp.com/api/short/tiny?url=$%7Bres.%7D&apikey=Urbaeexyz%60))
> //var linkplay = playlinks.data.result.link
> //if (!isPrem) return aruga.reply(from, `Karena anda bukan user Premium, silahkan download menggunakan link\n\nLink: ${linkplay}`, id)
> aruga.sendFileFromUrl(from, playlink, '', '', id)
> .catch(() => {
> aruga.reply(from, 'Error', id)
> })
> })
> })
> .catch(err => {
> console.log(err)
> aruga.reply(from, err.message, id)
> })
> break

try new feature
play3
i update

**Comment by Urbaeexyz** [comment]
> It has about a month so I think, It is the same code as the last version, only translated into Spanish which is my native language.
> 
> case prefix+'play'://silahkan kalian custom sendiri jika ada yang ingin diubah
> if (args.length == 0) return aruga.reply(from, `Para buscar canciones de youtube\n\nUsar: ${prefix}play título de la canción`, id)
> fetchJson(`http://docs-jojo.herokuapp.com/api/yt-search?q=${body.slice(6)}`)
> //fetchJson(`https://api.zeks.xyz/api/yts?q=${body.slice(6)}&apikey=${apikeyvinz}`)
> .then(async (res) => {
> console.log(color(`Nombre : ${pushname}\nNumero : ${serial.replace('@c.us', '')}\nJudul: ${res.result.result[0].title}\nDurasi: ${res.result.result[0].duration} detik`, 'aqua'))
> const thumbsd = res.result.result[0].thumbnails[0].url
> const thumbhd = res.result.result[0].thumbnails[1].url
> if (thumbhd == 0 || thumbhd == undefined) {
> var thumbnih = thumbsd
> } else {
> var thumbnih = thumbhd
> }
> //console.log(color(`Nickname : ${pushname}\nNomor : ${serial.replace('@c.us', '')}\nJudul: ${res.result[0].video.title}\nDurasi: ${res.result[0].video.duration} detik`, 'aqua'))
> /_await aruga.sendFileFromUrl(from, res.data.result.result[0].thumbnails[0].url, ``, `「 *PLAY* 」\n\nJudul: ${res.data.result.result[0].title}\nDurasi: ${res.data.result.result[0].duration} detik\nViews: ${res.data.result.result[0].viewCount.short}\nUploaded: ${res.data.result.result[0].publishedTime}\nChannel: ${res.data.result.result[0].channel.name}\n\n*_Wait, lagi ngirim Audionya_*`, id)_/
> //await aruga.sendFileFromUrl(from, res.result[0].video.thumbnail_src, 'thumb.jpg', `「 _PLAY_ 」\n\n_Title:_ ${res.result[0].video.title}\n_Duration:_ ${res.result[0].video.duration} detik\n_Views:_ ${res.result[0].video.views}\n_Uploaded:_ ${res.result[0].video.upload_date}\n_Channel:_ ${res.result[0].uploader.username}\n_Verified Channel:_ ${res.result[0].uploader.verified}\n_Url:_ ${res.result[0].video.url}\n\n*_Waitt, lagi ngirim Audionyaa__`, id) await aruga.sendFileFromUrl(from, thumbnih, 'thumb.jpg', `「 _PLAY_ 」\n\n_Titulo:* ${res.result.result[0].title}\n_Duracion:_ ${res.result.result[0].duration} Min\n_Views:_ ${res.result.result[0].viewCount.short}\n_Subido:_ ${res.result.result[0].publishedTime}\n_Canal:_ ${res.result.result[0].channel.name}\n_Url:_ ${res.result.result[0].link}\n\n*_Espere... estamos creando su Audio_*`, id)
> rugaapi.ymp3(`[https://youtu.be/${res.result.result[0].id}`](https://youtu.be/$%7Bres.result.result%5B0%5D.id%7D%60))
> .then(async(res) => {
> if (res.status == false) return aruga.reply(from, res.result, id)
> const playlink = res.result
> //var playlinks = await axios.get(`[https://urbaee-xyz.herokuapp.com/api/short/tiny?url=${res.}&apikey=Urbaeexyz`](https://urbaee-xyz.herokuapp.com/api/short/tiny?url=$%7Bres.%7D&apikey=Urbaeexyz%60))
> //var linkplay = playlinks.data.result.link
> //if (!isPrem) return aruga.reply(from, `Karena anda bukan user Premium, silahkan download menggunakan link\n\nLink: ${linkplay}`, id)
> aruga.sendFileFromUrl(from, playlink, '', '', id)
> .catch(() => {
> aruga.reply(from, 'Error', id)
> })
> })
> })
> .catch(err => {
> console.log(err)
> aruga.reply(from, err.message, id)
> })
> break

https://github.com/Urbaeexyz/wa-bot/commit/e5a9fc923960c48f6dca9c7dc8d8f7e7c343b008

**Comment by Stive889** [comment]
![image](https://user-images.githubusercontent.com/26675985/125376627-70438600-e359-11eb-9668-688ef8a98a8d.png)

the line:

![image](https://user-images.githubusercontent.com/26675985/125376710-98cb8000-e359-11eb-8dd4-e1e6f0b60d4a.png)

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/26675985/125376627-70438600-e359-11eb-9668-688ef8a98a8d.png)
> 
> the line:
> 
> ![image](https://user-images.githubusercontent.com/26675985/125376710-98cb8000-e359-11eb-8dd4-e1e6f0b60d4a.png)

delete await

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/26675985/125376627-70438600-e359-11eb-9668-688ef8a98a8d.png)
> 
> the line:
> 
> ![image](https://user-images.githubusercontent.com/26675985/125376710-98cb8000-e359-11eb-8dd4-e1e6f0b60d4a.png)

update, thanks for the issues
check it if it's still error

**Comment by Stive889** [comment]
RESOLVED, THANK YOU VERY MUCH FOR ALL THE SUPPORT

**Comment by Urbaeexyz** [comment]
> RESOLVED, THANK YOU VERY MUCH FOR ALL THE SUPPORT

is it play3 work on linux?
have a screenshot?

**Comment by Stive889** [comment]
Yes!!!! only the details such as duration and others are missing, but it works excellent with that is enough
![Screenshot_20210713-054219](https://user-images.githubusercontent.com/26675985/125430355-3ae162c9-deed-411f-bc84-9865741e65b2.jpg)

**Comment by Stive889** [comment]
![Screenshot_20210713-075929](https://user-images.githubusercontent.com/26675985/125448048-3f78cf1d-6f4c-4c0b-95d9-d33ac6467c66.jpg)

it was functional until this api key gave this error

**Comment by Urbaeexyz** [comment]
> ![Screenshot_20210713-075929](https://user-images.githubusercontent.com/26675985/125448048-3f78cf1d-6f4c-4c0b-95d9-d33ac6467c66.jpg)
> 
> it was functional until this api key gave this error

for the apikey
you should req apikey on the website for it
read on readme

**Comment by Stive889** [comment]
Ready, Thanks, I was confused by the words that the error said but that was the api key hahaha

**Comment by Urbaeexyz** [comment]
> Ready, Thanks, I was confused by the words that the error said but that was the api key hahaha

i will change for the title viewer upload date 
be patient

**Comment by Urbaeexyz** [comment]
> RESOLVED, THANK YOU VERY MUCH FOR ALL THE SUPPORT

update!

https://github.com/Urbaeexyz/wa-bot/commit/91953c35d294dc5013a9e11ab18a8f675032015a

**Comment by Urbaeexyz** [comment]
please make issues if it's have an error
