### ISSUE TITLE
Npm start error!..

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/wa-bot#43]
![Screenshot (58)](https://user-images.githubusercontent.com/76943884/125484881-e9564108-7549-4b60-8262-9ae3d9392959.png)

Session data most likely expired due to manual host account logout. Please re-authenticate this session.
I'm using old wa-bot repository. Does it have to do with that?

**Comment by Urbaeexyz** [comment]
> ![Screenshot (58)](https://user-images.githubusercontent.com/76943884/125484881-e9564108-7549-4b60-8262-9ae3d9392959.png)
> 
> Session data most likely expired due to manual host account logout. Please re-authenticate this session.
> I'm using old wa-bot repository. Does it have to do with that?

clone the new one

**Comment by Urbaeexyz** [comment]
or you can use this
`npm i --save @open-wa/wa-automate@latest`

**Comment by Harsh-beep** [comment]
> or you can use this
> `npm i --save @open-wa/wa-automate@latest`

Thanks It helped!
