### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/wa-bot#44]
Where can I find rest api sites?

**Comment by Urbaeexyz** [comment]
> Where can I find rest api sites?

https://github.com/Urbaeexyz/wa-bot#Information

**Comment by Harsh-beep** [comment]
> > Where can I find rest api sites?
> 
> https://github.com/Urbaeexyz/wa-bot#Information

I mean other sites..
There are many more rest api sites..
Where could I search for them?

**Comment by Urbaeexyz** [comment]
> > > Where can I find rest api sites?
> > 
> > 
> > https://github.com/Urbaeexyz/wa-bot#Information
> 
> I mean other sites..
> There are many more rest api sites..
> Where could I search for them?

search with other whatsapp-bot repository

**Comment by Harsh-beep** [comment]
> > > > Where can I find rest api sites?
> > > 
> > > 
> > > https://github.com/Urbaeexyz/wa-bot#Information
> > 
> > 
> > I mean other sites..
> > There are many more rest api sites..
> > Where could I search for them?
> 
> search with other whatsapp-bot repository

Aight thanks
