### ISSUE TITLE
Cara fix? 

### ISSUE THREAD

**Issue by MoziGuy** [Urbaeexyz/wa-bot#45]
Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya? 
![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)

**Comment by Urbaeexyz** [comment]
> Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya?
> ![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)

check update

**Comment by Urbaeexyz** [comment]
> Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya?
> ![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)

fixed https://github.com/Urbaeexyz/wa-bot/commit/c253a342c8778b24303431c77137d36e782fd4fd

**Comment by MoziGuy** [comment]
> > Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya?
> > ![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)
> 
> fixed [buka ini](https://github.com/Urbaeexyz/wa-bot/commit/c253a342c8778b24303431c77137d36e782fd4fd)

Still error
![16268312127192009263867530141892](https://user-images.githubusercontent.com/77720124/126416582-40ed3de1-672f-4632-95dd-1b88d8d27d74.jpg)

**Comment by MoziGuy** [comment]
> > > Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya?
> > > ![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)
> > 
> > 
> > fixed [buka ini](https://github.com/Urbaeexyz/wa-bot/commit/c253a342c8778b24303431c77137d36e782fd4fd)
> 
> Still error
> ![16268312127192009263867530141892](https://user-images.githubusercontent.com/77720124/126416582-40ed3de1-672f-4632-95dd-1b88d8d27d74.jpg)

Fixed, hapus bagian jame nya, cuman pas dibagian date/betime munculnya kek gini
![Screenshot_2021-07-21-08-46-32-752_com whatsapp~2](https://user-images.githubusercontent.com/77720124/126417681-b7a89bb2-8d07-44b9-a7ef-af5ac5ec2a58.jpg)

**Comment by Urbaeexyz** [comment]
> > > > Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya?
> > > > ![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)
> > > 
> > > 
> > > fixed [buka ini](https://github.com/Urbaeexyz/wa-bot/commit/c253a342c8778b24303431c77137d36e782fd4fd)
> > 
> > 
> > Still error
> > ![16268312127192009263867530141892](https://user-images.githubusercontent.com/77720124/126416582-40ed3de1-672f-4632-95dd-1b88d8d27d74.jpg)
> 
> Fixed, dah gw hapus bagian jame nya, cuman pas dibagian menu bagian date/betime munculnya kek gini
> ![Screenshot_2021-07-21-08-46-32-752_com whatsapp~2](https://user-images.githubusercontent.com/77720124/126417681-b7a89bb2-8d07-44b9-a7ef-af5ac5ec2a58.jpg)

wait

**Comment by Urbaeexyz** [comment]
> > > > Setiap mau #menu keluar gitu di cmd nya tapi command lain kek #play sama command lain bisa, knp ya?
> > > > ![16267999537195052814379147932411](https://user-images.githubusercontent.com/77720124/126364286-a8206b07-06bd-4079-b5fe-1631b1a157ed.jpg)
> > > 
> > > 
> > > fixed [buka ini](https://github.com/Urbaeexyz/wa-bot/commit/c253a342c8778b24303431c77137d36e782fd4fd)
> > 
> > 
> > Still error
> > ![16268312127192009263867530141892](https://user-images.githubusercontent.com/77720124/126416582-40ed3de1-672f-4632-95dd-1b88d8d27d74.jpg)
> 
> Fixed, dah gw hapus bagian jame nya, cuman pas dibagian menu bagian date/betime munculnya kek gini
> ![Screenshot_2021-07-21-08-46-32-752_com whatsapp~2](https://user-images.githubusercontent.com/77720124/126417681-b7a89bb2-8d07-44b9-a7ef-af5ac5ec2a58.jpg)

nihh

case prefix+'p':
case prefix+'start':
case prefix+'menu':
			const jame = moment(t * 1000).format('HH:mm:ss')
            const pictsx = 'https://i.ibb.co/WsPRR5G/baifern.jpg'
            aruga.sendFileFromUrl(from, pictsx, 'image.jpg', menuId.help(prefix, jame, betime, prem, blockNumber, banned, cts, waver), id)
            .then(() => ((isGroupMsg) && (isGroupAdmins)) ? aruga.sendText(from, `Menu Admin Grup: *${prefix}menuadmin*`) : null)
            break

**Comment by Urbaeexyz** [comment]
ini yg di menu

const help = (prefix, jame, betime, blockNumber, prem, banned, cts, waver) => {
    return `
*┏━──Information Bot*
*┃*
*┃➥ Repo : github.com/Urbaeexyz/wa-bot*
*┃➥ Library : @open-wa/wa-automate*
*┃➥ Bot Name : Urbaeexyz*
*┃➥ Whatsapp Bot Ver : 2.4.5*
*┃➥ Creator : Thoriq Azzikra*
*┃➥ Date : ${betime}*
*┃➥ Time : ${jame}*
*┃➥ Premium : ${blockNumber.length} User*
*┃➥ Banned : ${banned.length} User*
*┃➥ Block  : ${prem.length} User*
*┃*
*┗━──────────────*
