### ISSUE TITLE
Number Banned

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/wa-bot#47]
My whatsapp number got banned. 
How can I avoid banning? 
Any tips or help?

**Comment by Urbaeexyz** [comment]
> My whatsapp number got banned.
> How can I avoid banning?
> Any tips or help?

i do have get banned from whatsapp too and i send message with email to the whatsapp email and my number get unbanned

**Comment by Harsh-beep** [comment]
> > My whatsapp number got banned.
> > How can I avoid banning?
> > Any tips or help?
> 
> i do have get banned from whatsapp too and i send message with email to the whatsapp email and my number get unbanned

ThankU
