### ISSUE TITLE
Line ganti prefix bot

### ISSUE THREAD

**Issue by kazukikun24** [Urbaeexyz/wa-bot#49]
line nyandi mana bang.. work si. tapi gw mau set prefix nya gtw di mana pas gw pake di wa nya juga sama aja ga work mau -help #help juga ga iso

**Comment by Urbaeexyz** [comment]
> line nyandi mana bang.. work si. tapi gw mau set prefix nya gtw di mana pas gw pake di wa nya juga sama aja ga work mau -help #help juga ga iso

pake /
buat prefix ada di settings

**Comment by Urbaeexyz** [comment]
eh kalo ga salah multi prefix deh
coba pake / atau ga !

**Comment by Urbaeexyz** [comment]
https://github.com/Urbaeexyz/wa-bot/blob/20f90e6c18b5c2ba83cc7c2c5415524bafad701b/HandleMsg.js#L229
