### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by lucasjeronimoqd** [Urbaeexyz/wa-bot#5]
The bot displays the following error:
![Captura de tela 2021-03-10 155116](https://user-images.githubusercontent.com/72578140/110681875-11a6a980-81b9-11eb-9447-a8a8b040c7f3.png)

**Comment by buatrdp** [comment]
> > The bot displays the following error:
> > ![Captura de tela 2021-03-10 155116](https://user-images.githubusercontent.com/72578140/110681875-11a6a980-81b9-11eb-9447-a8a8b040c7f3.png)
> 
> that's error bcos npm itself not for script

https://reactgo.com/npm-err-cb-never-called/

**Comment by lucasjeronimoqd** [comment]
> vá atualizar seus nodejs e npm para versão mais recente

which version do i install? V14.16 or 15.11?

**Comment by Urbaeexyz** [comment]
> > vá atualizar seus nodejs e npm para versão mais recente
> 
> which version do i install? V14.16 or 15.11?

LATEST LTS version
