### ISSUE TITLE
Bot reply

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/wa-bot#50]
Bot is replying with every prefix even tho it's not set as prefix
how can i set only one prefix as main?

**Comment by Urbaeexyz** [comment]
> Bot is replying with every prefix even tho it's not set as prefix
> how can i set only one prefix as main?

[change this line and "global.prefix"](https://github.com/Urbaeexyz/wa-bot/blob/20f90e6c18b5c2ba83cc7c2c5415524bafad701b/HandleMsg.js#L229) into const prefix = "/"
