### ISSUE TITLE
nsfw feature erorr

### ISSUE THREAD

**Issue by aomineee** [Urbaeexyz/wa-bot#51]
![image](https://user-images.githubusercontent.com/87003965/127623034-ee1feb9f-625a-41a2-a37d-63ef71fc072f.png)
bang ini fitur bokep kok erorr ya

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/87003965/127623034-ee1feb9f-625a-41a2-a37d-63ef71fc072f.png)
> bang ini fitur bokep kok erorr ya

akwokaowa anjg:v

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/87003965/127623034-ee1feb9f-625a-41a2-a37d-63ef71fc072f.png)
> bang ini fitur bokep kok erorr ya

[nih dah ku fixed, kalo masih ga bisa kabarin lagi](https://github.com/Urbaeexyz/wa-bot/commit/a1f6adcdac19e3e4abc7d0e4f8a49e1d3166e07a)

**Comment by aomineee** [comment]
ok thanks bang
