### ISSUE TITLE
mystat feature erorr

### ISSUE THREAD

**Issue by aomineee** [Urbaeexyz/wa-bot#52]
![image](https://user-images.githubusercontent.com/87003965/127644668-5a0a8553-54de-4c98-9a18-d4717312887e.png)
kali ini mystat erorr wkwkw

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/87003965/127644668-5a0a8553-54de-4c98-9a18-d4717312887e.png)
> kali ini mystat erorr wkwkw

[nih dah di fixed](https://github.com/Urbaeexyz/wa-bot/commit/3ab40fec47db02bb04b65a256171cb1f51876cfa)

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/87003965/127644668-5a0a8553-54de-4c98-9a18-d4717312887e.png)
> kali ini mystat erorr wkwkw

fitur bokep dah bisa belom?
kalo udah di close issue nya om
