### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by fairyenzy** [Urbaeexyz/wa-bot#54]
Command 'exec' fungsi nya untuk apa ya kak?
Saya masih penasaran dengan itu, bisa dikasih contoh penggunaan nya?
Terimakasih.

**Comment by Urbaeexyz** [comment]
> Command 'exec' fungsi nya untuk apa ya kak?
> Saya masih penasaran dengan itu, bisa dikasih contoh penggunaan nya?
> Terimakasih.

itu buat owner bot, bisa dipake buat mengeksekusi perintah js, contoh
/exec aruga.sendText(from, 'Test')
