### ISSUE TITLE
Bot reply

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/wa-bot#55]
If I give command from bot no.s to itself. It isn't replying. How can I make bot to work on it's own commands?

**Comment by Urbaeexyz** [comment]
> If I give command from bot no.s to itself. It isn't replying. How can I make bot to work on it's own commands?

i think i have reply this issue before

you should change this line `const prefix = '/'`

**Comment by Harsh-beep** [comment]
> > If I give command from bot no.s to itself. It isn't replying. How can I make bot to work on it's own commands?
> 
> i think i have reply this issue before
> 
> you should change this line `const prefix = '/'`

No no no..
I want bot to reply if given command from bots number.

**Comment by Urbaeexyz** [comment]
> > > If I give command from bot no.s to itself. It isn't replying. How can I make bot to work on it's own commands?
> > 
> > 
> > i think i have reply this issue before
> > you should change this line `const prefix = '/'`
> 
> No no no..
> I want bot to reply if given command from bots number.
> Edit : Yes you replied to the issue but that was different and Thankyou very much for that.

ohh selfbot?
i have try that, but it's failed, sorry mate i can't help for this issue

**Comment by Harsh-beep** [comment]
> > > > If I give command from bot no.s to itself. It isn't replying. How can I make bot to work on it's own commands?
> > > 
> > > 
> > > i think i have reply this issue before
> > > you should change this line `const prefix = '/'`
> > 
> > 
> > No no no..
> > I want bot to reply if given command from bots number.
> > Edit : Yes you replied to the issue but that was different and Thankyou very much for that.
> 
> ohh selfbot?
> i have try that, but it's failed, sorry mate i can't help for this issue

Well it's ok then. Thanks...
